### ISSUE TITLE
It conflicts with phonegap-plugin-push

### ISSUE THREAD

**Issue by degaray** [transistorsoft/cordova-google-api-version#2]
I am trying to install this plugin to fix the '+' error due to google services. However it conflicts with phonegap-plugin-push. If I try to remove it, then it works, but when I install it back I still get the + error.

**Comment by christocracy** [comment]
This plugin won't work if any dependency uses `:+` for a google api.

**Comment by degaray** [comment]
I see. Is there any hack you can suggest?

**Comment by christocracy** [comment]
Fork offending repo using `:+`.  Set it to `:11.+`

**Comment by degaray** [comment]
In which file do I change that?

**Comment by christocracy** [comment]
Latest version of phonegap-plugin-push does not use `:+`.
https://github.com/phonegap/phonegap-plugin-push/blob/master/plugin.xml#L48
